# Generated by Django 5.1.2 on 2025-03-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
