# Generated by Django 5.1.2 on 2025-03-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_groupmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
    ]
