# Generated by Django 5.1.2 on 2025-03-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_groupmessage_file_groupmessage_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file_type',
        ),
    ]
