# Generated by Django 5.1.2 on 2025-03-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_groupmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
